Update README.md
From rails_admin issue #2405 it seems  --with-associations is necessary.
Also I had an error with 
.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activerecord-4.2.1/lib/active_record/dynamic_matchers.rb:26:in `method_missing': undefined method `has_paper_trail' for Provider (call 'Provider.connection' to establish a connection):Class (NoMethodError)
which was fixed by adding require paper_trail to application.rb